# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # subversions might be added
        java: [8, 9, 10, 11]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Java JDK version ${{ matrix.java }}
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ matrix.java }}
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checking out repository
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run the build python script
        run: python3 tools/build.py --dist

      # Runs a set of commands using the runners shell
      - name: Run regression tests
        run: python3 tools/run-test.py --init --print-log -sv 7.9.3 -scv 4.2.0.1873
        
